# Setup
# Find and Replace 'contentful' with the project name
# Make sure the volumes are not mapped to './app'
#

version: '3'
services:
  contentful-app:
    image: robmellett/lemp:7.4
    hostname: contentful-app
    container_name: contentful-app
    dns: 8.8.8.8
    env_file:
      - .docker.env
    environment:
      CONTAINER_ROLE: app # [app, horizon, queue, scheduler]
      APP_ENV: local # [local, staging, production]
    volumes:
      - ./:/var/www/html
    networks:
      - contentful
    ports:
      - 7000:80 # Web
      - 443:443 # Https
      - 7090:9100 # Prometheus, node_exporter
    tty: true

  contentful-mysql:
    image: mysql:latest
    hostname: contentful-mysql
    container_name: contentful-mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - contentful
    ports:
      - 3306:3306
    volumes:
      - contentful-db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root

volumes:
  contentful-db-data:

networks:
  contentful:
    driver: bridge
